insert into feed_type (id, name, plugin)
values (1, 'RSS 2.0', '(news-reader rss2)');

insert into languages (id, code3, code2, name)
values (0,'xxx','','Unknown')
       (1,'aar','aa','Afar'),
       (2,'abk','ab','Abkhazian'),
       (3,'ace','','Achinese'),
       (4,'ach','','Acoli'),
       (5,'ada','','Adangme'),
       (6,'ady','','Adyghe; Adygei'),
       (7,'afa','','Afro-Asiatic languages'),
       (8,'afh','','Afrihili'),
       (9,'afr','af','Afrikaans'),
       (10,'ain','','Ainu'),
       (11,'aka','ak','Akan'),
       (12,'akk','','Akkadian'),
       (13,'sqi','sq','Albanian'),
       (14,'ale','','Aleut'),
       (15,'alg','','Algonquian languages'),
       (16,'alt','','Southern Altai'),
       (17,'amh','am','Amharic'),
       (18,'ang','','English, Old (ca.450-1100)'),
       (19,'anp','','Angika'),
       (20,'apa','','Apache languages'),
       (21,'ara','ar','Arabic'),
       (22,'arc','','Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
       (23,'arg','an','Aragonese'),
       (24,'hye','hy','Armenian'),
       (25,'arn','','Mapudungun; Mapuche'),
       (26,'arp','','Arapaho'),
       (27,'art','','Artificial languages'),
       (28,'arw','','Arawak'),
       (29,'asm','as','Assamese'),
       (30,'ast','','Asturian; Bable; Leonese; Asturleonese'),
       (31,'ath','','Athapascan languages'),
       (32,'aus','','Australian languages'),
       (33,'ava','av','Avaric'),
       (34,'ave','ae','Avestan'),
       (35,'awa','','Awadhi'),
       (36,'aym','ay','Aymara'),
       (37,'aze','az','Azerbaijani'),
       (38,'bad','','Banda languages'),
       (39,'bai','','Bamileke languages'),
       (40,'bak','ba','Bashkir'),
       (41,'bal','','Baluchi'),
       (42,'bam','bm','Bambara'),
       (43,'ban','','Balinese'),
       (44,'eus','eu','Basque'),
       (45,'bas','','Basa'),
       (46,'bat','','Baltic languages'),
       (47,'bej','','Beja; Bedawiyet'),
       (48,'bel','be','Belarusian'),
       (49,'bem','','Bemba'),
       (50,'ben','bn','Bengali'),
       (51,'ber','','Berber languages'),
       (52,'bho','','Bhojpuri'),
       (53,'bih','bh','Bihari languages'),
       (54,'bik','','Bikol'),
       (55,'bin','','Bini; Edo'),
       (56,'bis','bi','Bislama'),
       (57,'bla','','Siksika'),
       (58,'bnt','','Bantu languages'),
       (59,'bod','bo','Tibetan'),
       (60,'bos','bs','Bosnian'),
       (61,'bra','','Braj'),
       (62,'bre','br','Breton'),
       (63,'btk','','Batak languages'),
       (64,'bua','','Buriat'),
       (65,'bug','','Buginese'),
       (66,'bul','bg','Bulgarian'),
       (67,'mya','my','Burmese'),
       (68,'byn','','Blin; Bilin'),
       (69,'cad','','Caddo'),
       (70,'cai','','Central American Indian languages'),
       (71,'car','','Galibi Carib'),
       (72,'cat','ca','Catalan; Valencian'),
       (73,'cau','','Caucasian languages'),
       (74,'ceb','','Cebuano'),
       (75,'cel','','Celtic languages'),
       (76,'ces','cs','Czech'),
       (77,'cha','ch','Chamorro'),
       (78,'chb','','Chibcha'),
       (79,'che','ce','Chechen'),
       (80,'chg','','Chagatai'),
       (81,'zho','zh','Chinese'),
       (82,'chk','','Chuukese'),
       (83,'chm','','Mari'),
       (84,'chn','','Chinook jargon'),
       (85,'cho','','Choctaw'),
       (86,'chp','','Chipewyan; Dene Suline'),
       (87,'chr','','Cherokee'),
       (88,'chu','cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
       (89,'chv','cv','Chuvash'),
       (90,'chy','','Cheyenne'),
       (91,'cmc','','Chamic languages'),
       (92,'cop','','Coptic'),
       (93,'cor','kw','Cornish'),
       (94,'cos','co','Corsican'),
       (95,'cpe','','Creoles and pidgins, English based'),
       (96,'cpf','','Creoles and pidgins, French-based'),
       (97,'cpp','','Creoles and pidgins, Portuguese-based'),
       (98,'cre','cr','Cree'),
       (99,'crh','','Crimean Tatar; Crimean Turkish'),
       (100,'crp','','Creoles and pidgins'),
       (101,'csb','','Kashubian'),
       (102,'cus','','Cushitic languages'),
       (103,'cym','cy','Welsh'),
       (104,'dak','','Dakota'),
       (105,'dan','da','Danish'),
       (106,'dar','','Dargwa'),
       (107,'day','','Land Dayak languages'),
       (108,'del','','Delaware'),
       (109,'den','','Slave (Athapascan)'),
       (110,'deu','de','German'),
       (111,'dgr','','Dogrib'),
       (112,'din','','Dinka'),
       (113,'div','dv','Divehi; Dhivehi; Maldivian'),
       (114,'doi','','Dogri'),
       (115,'dra','','Dravidian languages'),
       (116,'dsb','','Lower Sorbian'),
       (117,'dua','','Duala'),
       (118,'dum','','Dutch, Middle (ca.1050-1350)'),
       (119,'nld','nl','Dutch; Flemish'),
       (120,'dyu','','Dyula'),
       (121,'dzo','dz','Dzongkha'),
       (122,'efi','','Efik'),
       (123,'egy','','Egyptian (Ancient)'),
       (124,'eka','','Ekajuk'),
       (125,'ell','el','Greek, Modern (1453-)'),
       (126,'elx','','Elamite'),
       (127,'eng','en','English'),
       (128,'enm','','English, Middle (1100-1500)'),
       (129,'epo','eo','Esperanto'),
       (130,'est','et','Estonian'),
       (131,'ewe','ee','Ewe'),
       (132,'ewo','','Ewondo'),
       (133,'fan','','Fang'),
       (134,'fao','fo','Faroese'),
       (135,'fas','fa','Persian'),
       (136,'fat','','Fanti'),
       (137,'fij','fj','Fijian'),
       (138,'fil','','Filipino; Pilipino'),
       (139,'fin','fi','Finnish'),
       (140,'fiu','','Finno-Ugrian languages'),
       (141,'fon','','Fon'),
       (142,'fra','fr','French'),
       (143,'frm','','French, Middle (ca.1400-1600)'),
       (144,'fro','','French, Old (842-ca.1400)'),
       (145,'frr','','Northern Frisian'),
       (146,'frs','','Eastern Frisian'),
       (147,'fry','fy','Western Frisian'),
       (148,'ful','ff','Fulah'),
       (149,'fur','','Friulian'),
       (150,'gaa','','Ga'),
       (151,'gay','','Gayo'),
       (152,'gba','','Gbaya'),
       (153,'gem','','Germanic languages'),
       (154,'kat','ka','Georgian'),
       (155,'gez','','Geez'),
       (156,'gil','','Gilbertese'),
       (157,'gla','gd','Gaelic; Scottish Gaelic'),
       (158,'gle','ga','Irish'),
       (159,'glg','gl','Galician'),
       (160,'glv','gv','Manx'),
       (161,'gmh','','German, Middle High (ca.1050-1500)'),
       (162,'goh','','German, Old High (ca.750-1050)'),
       (163,'gon','','Gondi'),
       (164,'gor','','Gorontalo'),
       (165,'got','','Gothic'),
       (166,'grb','','Grebo'),
       (167,'grc','','Greek, Ancient (to 1453)'),
       (168,'grn','gn','Guarani'),
       (169,'gsw','','Swiss German; Alemannic; Alsatian'),
       (170,'guj','gu','Gujarati'),
       (171,'gwi','','Gwich''in'),
       (172,'hai','','Haida'),
       (173,'hat','ht','Haitian; Haitian Creole'),
       (174,'hau','ha','Hausa'),
       (175,'haw','','Hawaiian'),
       (176,'heb','he','Hebrew'),
       (177,'her','hz','Herero'),
       (178,'hil','','Hiligaynon'),
       (179,'him','','Himachali languages; Western Pahari languages'),
       (180,'hin','hi','Hindi'),
       (181,'hit','','Hittite'),
       (182,'hmn','','Hmong; Mong'),
       (183,'hmo','ho','Hiri Motu'),
       (184,'hrv','hr','Croatian'),
       (185,'hsb','','Upper Sorbian'),
       (186,'hun','hu','Hungarian'),
       (187,'hup','','Hupa'),
       (188,'iba','','Iban'),
       (189,'ibo','ig','Igbo'),
       (190,'isl','is','Icelandic'),
       (191,'ido','io','Ido'),
       (192,'iii','ii','Sichuan Yi; Nuosu'),
       (193,'ijo','','Ijo languages'),
       (194,'iku','iu','Inuktitut'),
       (195,'ile','ie','Interlingue; Occidental'),
       (196,'ilo','','Iloko'),
       (197,'ina','ia','Interlingua (International Auxiliary Language Association)'),
       (198,'inc','','Indic languages'),
       (199,'ind','id','Indonesian'),
       (200,'ine','','Indo-European languages'),
       (201,'inh','','Ingush'),
       (202,'ipk','ik','Inupiaq'),
       (203,'ira','','Iranian languages'),
       (204,'iro','','Iroquoian languages'),
       (205,'ita','it','Italian'),
       (206,'jav','jv','Javanese'),
       (207,'jbo','','Lojban'),
       (208,'jpn','ja','Japanese'),
       (209,'jpr','','Judeo-Persian'),
       (210,'jrb','','Judeo-Arabic'),
       (211,'kaa','','Kara-Kalpak'),
       (212,'kab','','Kabyle'),
       (213,'kac','','Kachin; Jingpho'),
       (214,'kal','kl','Kalaallisut; Greenlandic'),
       (215,'kam','','Kamba'),
       (216,'kan','kn','Kannada'),
       (217,'kar','','Karen languages'),
       (218,'kas','ks','Kashmiri'),
       (219,'kau','kr','Kanuri'),
       (220,'kaw','','Kawi'),
       (221,'kaz','kk','Kazakh'),
       (222,'kbd','','Kabardian'),
       (223,'kha','','Khasi'),
       (224,'khi','','Khoisan languages'),
       (225,'khm','km','Central Khmer'),
       (226,'kho','','Khotanese; Sakan'),
       (227,'kik','ki','Kikuyu; Gikuyu'),
       (228,'kin','rw','Kinyarwanda'),
       (229,'kir','ky','Kirghiz; Kyrgyz'),
       (230,'kmb','','Kimbundu'),
       (231,'kok','','Konkani'),
       (232,'kom','kv','Komi'),
       (233,'kon','kg','Kongo'),
       (234,'kor','ko','Korean'),
       (235,'kos','','Kosraean'),
       (236,'kpe','','Kpelle'),
       (237,'krc','','Karachay-Balkar'),
       (238,'krl','','Karelian'),
       (239,'kro','','Kru languages'),
       (240,'kru','','Kurukh'),
       (241,'kua','kj','Kuanyama; Kwanyama'),
       (242,'kum','','Kumyk'),
       (243,'kur','ku','Kurdish'),
       (244,'kut','','Kutenai'),
       (245,'lad','','Ladino'),
       (246,'lah','','Lahnda'),
       (247,'lam','','Lamba'),
       (248,'lao','lo','Lao'),
       (249,'lat','la','Latin'),
       (250,'lav','lv','Latvian'),
       (251,'lez','','Lezghian'),
       (252,'lim','li','Limburgan; Limburger; Limburgish'),
       (253,'lin','ln','Lingala'),
       (254,'lit','lt','Lithuanian'),
       (255,'lol','','Mongo'),
       (256,'loz','','Lozi'),
       (257,'ltz','lb','Luxembourgish; Letzeburgesch'),
       (258,'lua','','Luba-Lulua'),
       (259,'lub','lu','Luba-Katanga'),
       (260,'lug','lg','Ganda'),
       (261,'lui','','Luiseno'),
       (262,'lun','','Lunda'),
       (263,'luo','','Luo (Kenya and Tanzania)'),
       (264,'lus','','Lushai'),
       (265,'mkd','mk','Macedonian'),
       (266,'mad','','Madurese'),
       (267,'mag','','Magahi'),
       (268,'mah','mh','Marshallese'),
       (269,'mai','','Maithili'),
       (270,'mak','','Makasar'),
       (271,'mal','ml','Malayalam'),
       (272,'man','','Mandingo'),
       (273,'mri','mi','Maori'),
       (274,'map','','Austronesian languages'),
       (275,'mar','mr','Marathi'),
       (276,'mas','','Masai'),
       (277,'msa','ms','Malay'),
       (278,'mdf','','Moksha'),
       (279,'mdr','','Mandar'),
       (280,'men','','Mende'),
       (281,'mga','','Irish, Middle (900-1200)'),
       (282,'mic','','Mi''kmaq; Micmac'),
       (283,'min','','Minangkabau'),
       (284,'mis','','Uncoded languages'),
       (285,'mkh','','Mon-Khmer languages'),
       (286,'mlg','mg','Malagasy'),
       (287,'mlt','mt','Maltese'),
       (288,'mnc','','Manchu'),
       (289,'mni','','Manipuri'),
       (290,'mno','','Manobo languages'),
       (291,'moh','','Mohawk'),
       (292,'mon','mn','Mongolian'),
       (293,'mos','','Mossi'),
       (294,'mul','','Multiple languages'),
       (295,'mun','','Munda languages'),
       (296,'mus','','Creek'),
       (297,'mwl','','Mirandese'),
       (298,'mwr','','Marwari'),
       (299,'myn','','Mayan languages'),
       (300,'myv','','Erzya'),
       (301,'nah','','Nahuatl languages'),
       (302,'nai','','North American Indian languages'),
       (303,'nap','','Neapolitan'),
       (304,'nau','na','Nauru'),
       (305,'nav','nv','Navajo; Navaho'),
       (306,'nbl','nr','Ndebele, South; South Ndebele'),
       (307,'nde','nd','Ndebele, North; North Ndebele'),
       (308,'ndo','ng','Ndonga'),
       (309,'nds','','Low German; Low Saxon; German, Low; Saxon, Low'),
       (310,'nep','ne','Nepali'),
       (311,'new','','Nepal Bhasa; Newari'),
       (312,'nia','','Nias'),
       (313,'nic','','Niger-Kordofanian languages'),
       (314,'niu','','Niuean'),
       (315,'nno','nn','Norwegian Nynorsk; Nynorsk, Norwegian'),
       (316,'nob','nb','Bokmål, Norwegian; Norwegian Bokmål'),
       (317,'nog','','Nogai'),
       (318,'non','','Norse, Old'),
       (319,'nor','no','Norwegian'),
       (320,'nqo','','N''Ko'),
       (321,'nso','','Pedi; Sepedi; Northern Sotho'),
       (322,'nub','','Nubian languages'),
       (323,'nwc','','Classical Newari; Old Newari; Classical Nepal Bhasa'),
       (324,'nya','ny','Chichewa; Chewa; Nyanja'),
       (325,'nym','','Nyamwezi'),
       (326,'nyn','','Nyankole'),
       (327,'nyo','','Nyoro'),
       (328,'nzi','','Nzima'),
       (329,'oci','oc','Occitan (post 1500)'),
       (330,'oji','oj','Ojibwa'),
       (331,'ori','or','Oriya'),
       (332,'orm','om','Oromo'),
       (333,'osa','','Osage'),
       (334,'oss','os','Ossetian; Ossetic'),
       (335,'ota','','Turkish, Ottoman (1500-1928)'),
       (336,'oto','','Otomian languages'),
       (337,'paa','','Papuan languages'),
       (338,'pag','','Pangasinan'),
       (339,'pal','','Pahlavi'),
       (340,'pam','','Pampanga; Kapampangan'),
       (341,'pan','pa','Panjabi; Punjabi'),
       (342,'pap','','Papiamento'),
       (343,'pau','','Palauan'),
       (344,'peo','','Persian, Old (ca.600-400 B.C.)'),
       (345,'phi','','Philippine languages'),
       (346,'phn','','Phoenician'),
       (347,'pli','pi','Pali'),
       (348,'pol','pl','Polish'),
       (349,'pon','','Pohnpeian'),
       (350,'por','pt','Portuguese'),
       (351,'pra','','Prakrit languages'),
       (352,'pro','','Provençal, Old (to 1500);Occitan, Old (to 1500)'),
       (353,'pus','ps','Pushto; Pashto'),
       (354,'qaa','','Reserved for local use'),
       (355,'que','qu','Quechua'),
       (356,'raj','','Rajasthani'),
       (357,'rap','','Rapanui'),
       (358,'rar','','Rarotongan; Cook Islands Maori'),
       (359,'roa','','Romance languages'),
       (360,'roh','rm','Romansh'),
       (361,'rom','','Romany'),
       (362,'ron','ro','Romanian; Moldavian; Moldovan'),
       (363,'run','rn','Rundi'),
       (364,'rup','','Aromanian; Arumanian; Macedo-Romanian'),
       (365,'rus','ru','Russian'),
       (366,'sad','','Sandawe'),
       (367,'sag','sg','Sango'),
       (368,'sah','','Yakut'),
       (369,'sai','','South American Indian languages'),
       (370,'sal','','Salishan languages'),
       (371,'sam','','Samaritan Aramaic'),
       (372,'san','sa','Sanskrit'),
       (373,'sas','','Sasak'),
       (374,'sat','','Santali'),
       (375,'scn','','Sicilian'),
       (376,'sco','','Scots'),
       (377,'sel','','Selkup'),
       (378,'sem','','Semitic languages'),
       (379,'sga','','Irish, Old (to 900)'),
       (380,'sgn','','Sign Languages'),
       (381,'shn','','Shan'),
       (382,'sid','','Sidamo'),
       (383,'sin','si','Sinhala; Sinhalese'),
       (384,'sio','','Siouan languages'),
       (385,'sit','','Sino-Tibetan languages'),
       (386,'sla','','Slavic languages'),
       (387,'slk','sk','Slovak'),
       (388,'slv','sl','Slovenian'),
       (389,'sma','','Southern Sami'),
       (390,'sme','se','Northern Sami'),
       (391,'smi','','Sami languages'),
       (392,'smj','','Lule Sami'),
       (393,'smn','','Inari Sami'),
       (394,'smo','sm','Samoan'),
       (395,'sms','','Skolt Sami'),
       (396,'sna','sn','Shona'),
       (397,'snd','sd','Sindhi'),
       (398,'snk','','Soninke'),
       (399,'sog','','Sogdian'),
       (400,'som','so','Somali'),
       (401,'son','','Songhai languages'),
       (402,'sot','st','Sotho, Southern'),
       (403,'spa','es','Spanish; Castilian'),
       (404,'srd','sc','Sardinian'),
       (405,'srn','','Sranan Tongo'),
       (406,'srp','sr','Serbian'),
       (407,'srr','','Serer'),
       (408,'ssa','','Nilo-Saharan languages'),
       (409,'ssw','ss','Swati'),
       (410,'suk','','Sukuma'),
       (411,'sun','su','Sundanese'),
       (412,'sus','','Susu'),
       (413,'sux','','Sumerian'),
       (414,'swa','sw','Swahili'),
       (415,'swe','sv','Swedish'),
       (416,'syc','','Classical Syriac'),
       (417,'syr','','Syriac'),
       (418,'tah','ty','Tahitian'),
       (419,'tai','','Tai languages'),
       (420,'tam','ta','Tamil'),
       (421,'tat','tt','Tatar'),
       (422,'tel','te','Telugu'),
       (423,'tem','','Timne'),
       (424,'ter','','Tereno'),
       (425,'tet','','Tetum'),
       (426,'tgk','tg','Tajik'),
       (427,'tgl','tl','Tagalog'),
       (428,'tha','th','Thai'),
       (429,'tig','','Tigre'),
       (430,'tir','ti','Tigrinya'),
       (431,'tiv','','Tiv'),
       (432,'tkl','','Tokelau'),
       (433,'tlh','','Klingon; tlhIngan-Hol'),
       (434,'tli','','Tlingit'),
       (435,'tmh','','Tamashek'),
       (436,'tog','','Tonga (Nyasa)'),
       (437,'ton','to','Tonga (Tonga Islands)'),
       (438,'tpi','','Tok Pisin'),
       (439,'tsi','','Tsimshian'),
       (440,'tsn','tn','Tswana'),
       (441,'tso','ts','Tsonga'),
       (442,'tuk','tk','Turkmen'),
       (443,'tum','','Tumbuka'),
       (444,'tup','','Tupi languages'),
       (445,'tur','tr','Turkish'),
       (446,'tut','','Altaic languages'),
       (447,'tvl','','Tuvalu'),
       (448,'twi','tw','Twi'),
       (449,'tyv','','Tuvinian'),
       (450,'udm','','Udmurt'),
       (451,'uga','','Ugaritic'),
       (452,'uig','ug','Uighur; Uyghur'),
       (453,'ukr','uk','Ukrainian'),
       (454,'umb','','Umbundu'),
       (455,'und','','Undetermined'),
       (456,'urd','ur','Urdu'),
       (457,'uzb','uz','Uzbek'),
       (458,'vai','','Vai'),
       (459,'ven','ve','Venda'),
       (460,'vie','vi','Vietnamese'),
       (461,'vol','vo','Volapük'),
       (462,'vot','','Votic'),
       (463,'wak','','Wakashan languages'),
       (464,'wal','','Wolaitta; Wolaytta'),
       (465,'war','','Waray'),
       (466,'was','','Washo'),
       (467,'wen','','Sorbian languages'),
       (468,'wln','wa','Walloon'),
       (469,'wol','wo','Wolof'),
       (470,'xal','','Kalmyk; Oirat'),
       (471,'xho','xh','Xhosa'),
       (472,'yao','','Yao'),
       (473,'yap','','Yapese'),
       (474,'yid','yi','Yiddish'),
       (475,'yor','yo','Yoruba'),
       (476,'ypk','','Yupik languages'),
       (477,'zap','','Zapotec'),
       (478,'zbl','','Blissymbols; Blissymbolics; Bliss'),
       (479,'zen','','Zenaga'),
       (480,'zgh','','Standard Moroccan Tamazight'),
       (481,'zha','za','Zhuang; Chuang'),
       (482,'znd','','Zande languages'),
       (483,'zul','zu','Zulu'),
       (484,'zun','','Zuni'),
       (485,'zxx','','No linguistic content; Not applicable'),
       (486,'zza','','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki');

